# SITE CONFIGURATION
baseurl: ""
url: "https://ciberninjas.com"
title: "Ciberninjas"
description: Actualidad, noticias y eventos de desarrollo web, programación y diseño; para desarrolladores, programadores y diseñadores de habla hispana. 
# Configuración
author: Pablo Álvarez Corredera
# : Libros PDF, cursos, tutoriales y eventos
avatar: '/assets/img/ciberninjas-emoji-160px.webp'
favicon: 'assets/favicon.ico'
# Header and footer text
header_text: 'Jardín Digital del Saber Binario'
header_feature_image: '/assets/img/portada.webp'
footer_text: >
  © 2020 Ciberninjas. Actualidad, noticias y eventos de desarrollo web, programación y diseño.<br/> Creado desde Asturias. Con Jekyll y <a href="https://github.com/sylhare/Type-on-Strap" target="_blank" rel="nofollow,noreferrer">Type on Strap</a>

# Blog
excerpt: false                                       # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.webp                    # A bit transparent for color posts.
# Features
katex: true                                          # Enable if using math markup
google_analytics: "UA-142542230-1  "                      # Tracking ID, e.g. "UA-000000-01"
cookie_consent: true                                     # To respect the usage of cookies
cookie_consent_disclaimer: Nos gustaría utilizar cookies y scripts para mejorar la funcionalidad de la web. <a href="https://ciberninjas.com/aviso-legal/">Saber Más</a>
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml
# SEO
lang: es_ES
seo:
  name: "Ciberninjas: El Jardín Digital del Saber Binario"
# PAGINATION
paginate: 10
paginate_path: "/blog/page:num"
# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name
  guias:
    output: true
    permalink: /:collection/:name
  eff:
    output: true
    permalink: /:collection/:name
  programa-gratis:
    output: true
    permalink: /:collection/:name
  libros-prog:
    output: true
    permalink: /:collection/:name
  cursos-gratis:
    output: true
    permalink: /:collection/:name
  wiki:
    output: true
    permalink: /:collection/:name
  glosario:
    output: true
    permalink: /:collection/:name
  catalogo:
    output: true
    permalink: /:collection/:name
  historia-computadora:
    output: true
    permalink: /:collection/:name
  personajes-historicos:
    output: true
    permalink: /:collection/:name
  pac:
    output: true
    permalink: /:collection/:name
  amazon:
    output: true
    permalink: /:collection/:name
  biblioteca:
    output: true
    permalink: /:collection/:name
  cursos-bases-datos:
    output: true
    permalink: /:collection/:name
  cursos-fk-prog:
    output: true
    permalink: /:collection/:name
# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]
# Tema: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
