# SITE CONFIGURATION
baseurl: ""
url: "https://ciberninjas.com"
title: "Ciberninjas"
description: Noticias, actualidad y eventos de desarrollo web, programaci칩n y dise침o; para desarrolladores, programadores y dise침adores de habla hispana. 
# Configuraci칩n
author: ROSEPAC
avatar: '/assets/img/ciberninjas-emoji-160px.webp'
favicon: 'assets/favicon.ico'
feed:
  posts_limit: 1000
feed:
  collections:
    - portfolio
    - guias
    - eff
    - programa-gratis
    - libros-prog
    - cursos-gratis
    - wiki
    - glosario
    - catalogo
    - historia-computadora
    - personajes-historicos
    - pac
    - amazon
    - biblioteca
    - cursos-bases-datos
    - cursos-fk-prog
    - fpdaw
# Header and footer text
header_text: 'Blog de Desarrolladores Ninja'
header_feature_image: '/assets/img/paginas/navidad-cartel-cn.webp'
footer_text: >-
 춸 2020 Ciberninjas. Noticias, cursos, eventos y art칤culos de desarrollo web, programaci칩n y dise침o.<br/> Con 游떁 desde Asturias. Lanzado por Jekyll y <a href="https://github.com/sylhare/Type-on-Strap" target="_blank" rel="nofollow,noreferrer">Type on Strap</a>
# Blog
excerpt: false                                       # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.webp                    # A bit transparent for color posts.
# Features
katex: false                                          # Enable if using math markup
google_analytics: "UA-142542230-1"                      # Tracking ID, e.g. "UA-000000-01"
cookie_consent: true                                    # To respect the usage of cookies
cookie_consent_disclaimer: Nos gustar칤a utilizar cookies y scripts para mejorar la funcionalidad de la web. <span style="color:white"><a href="https://ciberninjas.com/aviso-legal/">Saber M치s</a></span>
# SEO
lang: es_ES
logo: https://ciberninjas.com/assets/img/ciberninjas-emoji-160px.webp
seo:
  name: "Ciberninjas: El Jard칤n Digital del Saber Binario"
twitter:
  username: ciberninjas
  card: summary_large_image
# social:
#   name: Ciberninjas
#   links:
#     - https://twitter.com/ciberninjas
#     - https://www.facebook.com/ciberninjas
#     - https://www.linkedin.com/in/ciberninjas
#     - https://dev.to/rosepac
#     - https://t.me/ciberninjas
#     - https://github.com/rosepac
#     - https://instagram.com/ciberninjas

# PAGINATION
paginate: 10
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name
  guias:
    output: true
    permalink: /:collection/:name
  eff:
    output: true
    permalink: /:collection/:name
  programa-gratis:
    output: true
    permalink: /:collection/:name
  libros-prog:
    output: true
    permalink: /:collection/:name
  cursos-gratis:
    output: true
    permalink: /:collection/:name
  wiki:
    output: true
    permalink: /:collection/:name
  glosario:
    output: true
    permalink: /:collection/:name
  catalogo:
    output: true
    permalink: /:collection/:name
  historia-computadora:
    output: true
    permalink: /:collection/:name
  personajes-historicos:
    output: true
    permalink: /:collection/:name
  pac:
    output: true
    permalink: /:collection/:name
  amazon:
    output: true
    permalink: /:collection/:name
  biblioteca:
    output: true
    permalink: /:collection/:name
  cursos-bases-datos:
    output: true
    permalink: /:collection/:name
  cursos-fk-prog:
    output: true
    permalink: /:collection/:name
  fpdaw:
    output: true
    permalink: /:collection/:name
# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]
# Tema: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
