# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Configuraci√≥n de la Web
locale: "es-ES"
# timezone: "Europe/Madrid"
# github: [metadata]
title: Ciberninjas ‚ñ∑ Escuela Laboratorio
# subtitle: Escuela Laboratorio de Tecnolog√≠a
email: rosepac21@gmail.com
name: "Pablo √Ålvarez Corredera"
description: >- # this means to ignore newlines until "baseurl:"
  'Biblioteca de Libros, Cursos, Art√≠culos y Recursos para Aprender de Tecnolog√≠a: Aprender y Estudiar. El sitio perfecto para estudiantes, profesores, desarrolladores web y dise√±adores.'
url: "https://ciberninjas.com"
# baseurl:
repository: "rosepac/ciberninjas"
# teaser: "/assets/images/logos/ciberninjas-emoji-160-110px.png"
logo: "/assets/images/logos/ciberninjas-emoji-110px-sin-borde.png"
masthead_title: "Ciberninjas"
twitter_username: ciberaprendiz
github_username: Pablo √Ålvarez Corredera
minimal_mistakes_skin: default # default, air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise

# Configuraci√≥n del Autor
author:
  name   : "Pablo √Ålvarez Corredera"
  avatar : "/assets/images/bio-photo.png"
  bio    : "Documentalista Digital. Educaci√≥n Siglo XXI. Bibliotecario de Internet."
  links:
    - label: "Inv√≠tame"
      icon: "fas fa-fw fa-mug-hot"
      url: "https://kutt.it/Cafe"
    - label: "Donativo"
      icon: "fab fa-cc-paypal"
      url: "https://kutt.it/donativo"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rosepac"
    - label: "Universo Ciberninjas"
      icon: "fas fa-user-ninja"
      url: "https://linktr.ee/ciberninjas"

search: true
search_full_content: true
google:
  search_engine_id: 011189616958132448188:saiveewehsx

# search_provider: algolia
# algolia:
#   application_id: XV7A2DHT2U # YOUR_APPLICATION_ID
#   index_name: ciberninjas # YOUR_INDEX_NAME
#   search_only_api_key: 5e5cf6a882e0e96a52942bbd15eb7fe2 # YOUR_SEARCH_ONLY_API_KEY
#   powered_by: false # true (default), false
#   files_to_exclude:
#     # - _posts/2019-09-11-las-mejores-agendas-escolares-2019.md 
#     # - _posts/2017-11-28-post-exclude-search.md
#     - _pages/mapa-web.md

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:title/
paginate: 7 # amount of posts to show
paginate_path: /hoja:num/
timezone: Europe/Madrid

include:
  - _pages
#  - _glosario

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- editorial
- _staff-miembros
# Excluido por peticion del buscador algoria
# exclude: [vendor]

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
#  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-142542230-1"
    anonymize_ip: true # default
    
naver_site_verification: "6c9e3c9861eb717f29638c631ff91d7de609f9d4"

# Colecciones / Secciones Creadas
collections:
    guias:
        output: true
        permalink: /:collection/:path
    catalogo:
        output: true
        permalink: /:collection/:path
    biblioteca:
        output: true
        permalink: /:collection/:path
#    staff-miembros:
#        output: true
#        permalink: /:collection/:path
    glosario:
        output: true
        permalink: /:collection/:path
    wiki:
        output: true
        permalink: /:collection/:path
    historia-computadora:
        output: true
        permalink: /:collection/:path
    personajes-historicos:
        output: true
        permalink: /:collection/:path
    eff:
        output: true
        permalink: /:collection/:path
    pac:
        output: true
        permalink: /:collection/:path
    amazon:
        output: true
        permalink: /:collection/:path

defaults:
    # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      red_time: true
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _staff-miembros
#  - scope:
#      path: ""
#      type: staff-miembros
#    values:
#      layout: single
#      author_profile: true
#      read_time: true
#      comments: true
#      share: true
#      related: true
  # _guias
  - scope:
      path: ""
      type: guias
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false
  # _catalogo
  - scope:
      path: ""
      type: catalogo
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false
    # _biblioteca
  - scope:
      path: ""
      type: biblioteca
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _glosario
  - scope:
      path: ""
      type: glosario
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false
      # sidebar:
      # nav: main
      # sidebar:
        # nav: "docs"
  # _wiki
  - scope:
      path: ""
      type: wiki
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false
  # _historia-computadora
  - scope:
      path: ""
      type: historia-computadora
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false
  # _personajes-historicos
  - scope:
      path: ""
      type: personajes-historicos
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
    # _electronic-frontier-foundation
  - scope:
      path: ""
      type: eff
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false
  - scope:
      path: ""
      type: pac
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: amazon
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categoria/
tag_archive:
  type: liquid
  path: /etiqueta/

comments:
  provider: "disqus"
  disqus:
    shortname: "ciberninjas"

# Pie de P√°gina
footer:
  links:
    - label: "Donativo"
      icon: "fab fa-fw fa-paypal"
      url: "https://paypal.me/ciberninjas"
    - label: "Bitcoin"
      icon: "fab fa-fw fa-bitcoin"
      url: "14GGQUBou7EWvutCmgP8yajsWbrngk3DqT"
    - label: "Ethereum"
      icon: "fab fa-fw fa-ethereum"
      url: "0x9b039b7F5c7eE7D56C0C5cDB8E7E3720F126F4B7"
    - label: "Criptomonedas"
      icon: "fas fa-fw fa-donate"
      url: "https://gist.github.com/rosepac/df7d4fc0abcf6030c32907b9aa19c401#paypal"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ciberninjas"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/ciberninjas"
      
# Final de la Configuraci√≥n üíãüíãüíã