# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Configuraci贸n de la Web
locale: "es-ES"
# github: [metadata]
title:  Educaci贸n Digital >> Desarrollo M贸vil y Web >> Programaci贸n y Rob贸tica >> Herramientas del Mundo Tecnol贸gico
# subtitle: Escuela Laboratorio de Tecnolog铆a
email: rosepac21@gmail.com
name: "Pablo Alvarez Corredera"
description: >- # this means to ignore newlines until "baseurl:"
  'Los mejores libros y herramientas para aprender a programar como un aut茅ntico profesional. Los recursos m谩s brillantes y excelentes'
url: "https://ciberninjas.com"
# baseurl:
repository: "rosepac/ciberninjas"
head_scripts:
  - /assets/js/lazysizes.min.js
teaser: "/assets/images/logos/desarrollador-full-stack-1.webp"
logo: "/assets/images/logos/emoji-ciberninjas.png"
masthead_title: "Ciberninjas"
twitter_username: ciberaprendiz
github_username: Pablo lvarez Corredera
minimal_mistakes_skin: default # default, air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise
# Configuraci贸n del Autor
author:
  name   : "Pablo lvarez Corredera"
  avatar : "/assets/images/logos/rosepac-fullstack_160px.webp"
  bio    : "Documentalista Digital. Educaci贸n Siglo XXI. Bibliotecario de Internet."
  links:
    - label: "Correo"
      icon: "far fa-envelope"
      url: "mailto:rosepac21@gmail.com"    
    - label: "Enlaces"
      icon: "fas fa-anchor"
      url: "https://linktr.ee/ciberninjas"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rosepac"
    - label: "Cervecita!"
      icon: "fas fa-beer"
      url: "https://kutt.it/donativo"
    - label: "Lector RSS"  
      icon: "fas fa-rss-square"
      url: "https://feeds.feedburner.com/ciberninjas"
search: true
search_full_content: true
google:
  search_engine_id: 011189616958132448188:saiveewehsx
show_excerpts: true
# search_provider: algolia
# algolia:
#   application_id: XV7A2DHT2U # YOUR_APPLICATION_ID
#   index_name: ciberninjas # YOUR_INDEX_NAME
#   search_only_api_key: 5e5cf6a882e0e96a52942bbd15eb7fe2 # YOUR_SEARCH_ONLY_API_KEY
#   powered_by: false # true (default), false
#   files_to_exclude:
#     # - _posts/2019-09-11-las-mejores-agendas-escolares-2019.md 
#     # - _posts/2017-11-28-post-exclude-search.md
#     - _pages/mapa-web.md

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/Madrid"

include:
  - _pages
#  - _glosario

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- editorial
- _staff-miembros
- .vscode
# Excluido por peticion del buscador algoria
# exclude: [vendor]

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-gist
  - jekyll-feed
  - jemoji
#  - jekyll-sitemap

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-142542230-1"
    anonymize_ip: true # default
    
naver_site_verification: "6c9e3c9861eb717f29638c631ff91d7de609f9d4"

# Colecciones / Secciones Creadas
collections:
    guias:
        output: true
        permalink: /:collection/:path
    catalogo:
        output: true
        permalink: /:collection/:path
    biblioteca:
        output: true
        permalink: /:collection/:path
#    staff-miembros:
#        output: true
#        permalink: /:collection/:path
    glosario:
        output: true
        permalink: /:collection/:path
    wiki:
        output: true
        permalink: /:collection/:path
    historia-computadora:
        output: true
        permalink: /:collection/:path
    personajes-historicos:
        output: true
        permalink: /:collection/:path
    eff:
        output: true
        permalink: /:collection/:path
    pac:
        output: true
        permalink: /:collection/:path
    amazon:
        output: true
        permalink: /:collection/:path
    videotutoriales:
        output: true
        permalink: /:collection/:path

defaults:
    # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      red_time: true
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false
  # _staff-miembros
#  - scope:
#      path: ""
#      type: staff-miembros
#    values:
#      layout: single
#      author_profile: true
#      read_time: true
#      comments: false
#      share: true
#      related: false
  # _guias
  - scope:
      path: "_guias"
      type: guias
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: false
  # _catalogo
  - scope:
      path: "_catalogo"
      type: catalogo
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: false
    # _biblioteca
  - scope:
      path: "_biblioteca"
      type: biblioteca
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false
  # _glosario
  - scope:
      path: "_glosario"
      type: glosario
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: false
      # sidebar:
      # nav: main
      # sidebar:
        # nav: "docs"
  # _wiki
  - scope:
      path: "_wiki"
      type: wiki
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: false
  # _historia-computadora
  - scope:
      path: "_historia-computadora"
      type: historia-computadora
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: false
  # _personajes-historicos
  - scope:
      path: "_personajes-historicos"
      type: personajes-historicos
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: false
    # _electronic-frontier-foundation
  - scope:
      path: "_eff"
      type: eff
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: false
  - scope:
      path: "_pac"
      type: pac
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false
  - scope:
      path: "_amazon"
      type: amazon
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false
  - scope:
      path: "_videotutoriales"
      type: videotutoriales
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false

category_archive:
  type: liquid
  path: /categoria/
tag_archive:
  type: liquid
  path: /etiqueta/

# comments:
#   provider: "facebook"
#   facebook:
#     num_posts: 10 # 5 (default)

# Pie de P谩gina
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ciberninjas"
    - label: "Comunidad"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/groups/ciberninjas"
    - label: "CiberCursos"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/cibercursos"
    - label: "Aviso Legal"
      icon: "fas fa-shield-alt"
      url: "/aviso-legal/"
      
# Final de la Configuraci贸n